# Problem 1

In [1]:
pip install numpy #numpyı bilgisayarımıza kuruyoruz

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris= np.random.randint(0,10,5) 
print(matris)
# 3 - matris'in boyutunu öğrenin
print(matris.shape)
# 4 - matris'i yeniden boyutlandırın
new_matris=matris.reshape(5,1)
print(new_matris)
# 5 - matris'in boyut sayısını öğrenin
print(new_matris.ndim)

[1 8 9 4 8]
(5,)
[[1]
 [8]
 [9]
 [4]
 [8]]
2


# Problem 2

In [23]:
import numpy as np
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris_teksayi= np.arange (1,10,2)
print(matris_teksayi)
# 2 - Oluşturduğunuz matrisi parçalayın
matris_teksayi=np.split(matris_teksayi,[2,3])
print(matris_teksayi)
# 3 - Parçalanmış matrisleri birleştirin
array_1= [1,3]
array_2=[5]
array_3=[7,9]
print(np.concat([array_1,array_2,array_3]))

[1 3 5 7 9]
[array([1, 3]), array([5]), array([7, 9])]
[1 3 5 7 9]


# Problem 3

In [29]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matrisi yazdırın.
import numpy as np

matris= np.arange(5,100,2)
print(matris) #5 ile 100 arası ikişer artan matris

matris_random=np.random.randint(5,100,10)
print(matris_random) #bu matrisin içinden rastgele 10 sayı

# 2 - matris'in özelliklerini inceleyin
print(matris_random.ndim)
print(matris_random.shape)
print(matris_random.size)
print(matris_random.dtype)


[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]
[93 90 66 33 99 92 13 91 46 60]
1
(10,)
10
int32
