# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np 
# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([9,8,4,5,7,])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sorted_a=np.sort(a)
print(sorted_a)

[4 5 7 8 9]


# Problem 2

In [35]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.arange(10,60)
print(a[0::5])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b= np.arange(5,15)
print(b)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c= np.arange(50,100)
print(c[0::5])

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d=np.zeros(10)
print(d)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e= np.ones(10)
print(e)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f= np.linspace(0, 100, 5)
print(f)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g= np.random.randint(10, 31, 5)
print(g)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
ğ=np.random.randint(-1,1,10)
print(ğ)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
h=np.random.randint(10,50,size=[3,5])
print(h)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satır_toplam=np.sum(h,axis=1)
sütun_toplam=np.sum(h,axis=0)
print(satır_toplam)
print(sütun_toplam)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_büyük=np.max(h)
print(en_büyük)
en_küçük=np.min(h)
print(en_küçük)
ortalama=np.mean(h)
print(ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
sort_h=np.sort(h)
print(sort_h[0:1])

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi= np.arange(10,20)
print(dizi[0:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
ters_dizi= dizi[::-1]
print(ters_dizi)

# 15- Üretilen matrisin ilk satırını seçiniz.
print(h[0:1])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(h[1:2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(h[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(h**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
yeni_matris= np.random.randint(-50,50,size=[3,5])
print(yeni_matris)
print(yeni_matris> 0)

[10 15 20 25 30 35 40 45 50 55]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[12 25 28 23 17]
[ 0  0 -1 -1  0  0 -1  0 -1  0]
[[17 24 46 38 39]
 [27 41 22 22 34]
 [29 28 25 26 35]]
[164 146 143]
[ 73  93  93  86 108]
46
17
30.2
[[17 24 38 39 46]]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[[17 24 46 38 39]]
[[27 41 22 22 34]]
[17 27 29]
[[ 289  576 2116 1444 1521]
 [ 729 1681  484  484 1156]
 [ 841  784  625  676 1225]]
[[ -8 -14  16  12  12]
 [ 40  -2 -33  48  39]
 [ 25   0   1  43  47]]
[[False False  True  True  True]
 [ True False False  True  True]
 [ True False  True  True  True]]
